POST http://192.168.1.220/api?cmd=power&param=on HTTP/1.1
content-type: application/json

{

}

#############################
POST http://192.168.1.220/api?cmd=power&param=off HTTP/1.1
content-type: application/json

{

}

###############################
POST http://192.168.1.220/api?cmd=mode&param=natural HTTP/1.1
content-type: application/json

{

}

###############################
POST http://192.168.1.220/api?cmd=mode&param=relax HTTP/1.1
content-type: application/json

{

}

